
CREATE TABLE `application_data_table` (
  `APP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` int(11) DEFAULT NULL,
  `TOKEN_ID` varchar(100) DEFAULT NULL,
  `DEVICE_SOURCE` varchar(100) DEFAULT NULL,
  `SUCCESS_URL` varchar(100) DEFAULT NULL,
  `FAILURE_URL` varchar(100) DEFAULT NULL,
 	PRIMARY KEY (`APP_ID`)
)