
CREATE TABLE `merchant_account_data_table` (
  `ACCOUNT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MERCHANT_ID` int(11) DEFAULT NULL,
  `ACCOUNT_HOLDER_NAME` varchar(50) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(100) DEFAULT NULL,
  `IFSC_CODE` varchar(100) DEFAULT NULL,
  `BANK_NAME` varchar(100) DEFAULT NULL,
 PRIMARY KEY (`ACCOUNT_ID`)
)