

CREATE TABLE `payment_gateway_map_table` (
  `MAP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PAYMENT_GATEWAY_ID` int(11) DEFAULT NULL,
  `APPLICATION_ID` int(11) DEFAULT NULL,
  `PAYMENT_OPTION` varchar(100) DEFAULT NULL,
 	PRIMARY KEY (`MAP_ID`)
)